#!/usr/bin/env bash

gh/hosts.yml                                gh/hosts.yml
git/.gitconfig                              .gitconfig
nvim/init.lua                               nvim/init.lua
powershell/Microsoft.PowerShell_profile.ps1 powershell/Microsoft.PowerShell_profile.ps1
zsh/.zshrc                                  .zshrc
